### ISSUE TITLE
Comment the plots!

### ISSUE THREAD

**Issue by const-maslov** [theor-mephi/quark-matter-bugrus#2]
I don't get what is shown on the last plot, unless you have axes labels or comments for the figure.
And anyway you got strange behavior - all functions in the problem are rather smooth, aren't they?

P.S. Use cycles if you have more than 2 items. It's hard to change if written like 
```python
plt.plot(x_range,[Norm(x,x_fermi(0.4,x),0) for x in x_range])
plt.plot(x_range,[Norm(x,x_fermi(0.5,x),0) for x in x_range])
plt.plot(x_range,[Norm(x,x_fermi(0.6,x),0) for x in x_range])
plt.plot(x_range,[Norm(x,x_fermi(0.7,x),0) for x in x_range])
```

**Comment by bugrus** [comment]
At that moment x_fermi had seriously problem in it structure. Kernel was dying every time I tried plot the functions.
